### PR TITLE
referral page new design

### PR DESCRIPTION
**Pull request by Buda9**
If it aligns with your overall vision, feel free to merge it :)

Screenshot_103

### CODE REVIEW

**Comment by fmido88** [comment]
Great look, thanks @Buda9 
just there is some concerns
1st I'm not with using html inside a php file, its ok I know but instead we use mustache files to render it
2nd using style tag inside html is not effective, we could add it to styles.css instead to be loaded and saved in cashes along other css in the site.
I'll test it and inform you with modifications needed.

**Comment by Buda9** [comment]
Thank you. I'll start working on mustache and move assets to proper place

**Comment by fmido88** [comment]
Hello @Buda9;
I hope you doing good

I tried to modify the code and integrate it on the plugin, but there is one problem that the icons not appears
image

**Comment by fmido88** [comment]
Solved by adding "fa" to the classes of the icons

image

**Comment by fmido88** [comment]
I don't think we need viber, may be telegram would be better, don't you think?

**Comment by Buda9** [comment]
> I don't think we need viber, may be telegram would be better, don't you think?

Thank you so much. Yes, telegram would be much better option. Can you just tell me am I needed here or you're almost done?

**Comment by fmido88** [comment]
Hello @Buda9 
Yes please, If you don't mind take a look on the referral page final formatting and see if there is any more modification and suggestions.

**Pull request closed without merging**
